language: cpp
compiler:
  - clang
script: scons construct
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libv8-dev libeigen3-dev
    libglew-dev libxinerama-dev libgl1-mesa-dev libboost-all-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - cmake .
  - make
  - sudo make install
  - cd ..
