language: cpp
compiler:
  - clang
script: scons construct
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libv8-dev libeigen3-dev libjsoncpp-dev
    libglew-dev libglfw-dev libxinerama-dev libgl1-mesa-dev libboost-all-dev
    xorg-dev x11proto-xf86vidmode-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - cmake -DCMAKE_INSTALL_PREFIX=/usr .
  - make
  - sudo make install
  - cd ..
